/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.order;

import business.Flight;
import business.FlightCatalog;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author runyangzhou
 */
public class OrderJPanel extends javax.swing.JPanel {
    private JPanel displayJPanel;
    private FlightCatalog flightCatalog;
    /**
     * Creates new form OrderJPanel
     */
    public OrderJPanel(JPanel displayJPanel, FlightCatalog flightCatalog) {
        initComponents();
        this.displayJPanel = displayJPanel;
        this.flightCatalog = flightCatalog;
        populate();
    }
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel) tblSeats.getModel();
        dtm.setRowCount(0);
        
        for(Flight flight : flightCatalog.getFlightList()){
            int[][] seats = flight.getSeats();
            for(int i = 0; i < 25; i++)
                for(int j = 0; j < 6; j++){
                    if(seats[i][j] == 0){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0] = flight;
                    row[1] = flight.getDepartureAirport();
                    row[2] = flight.getArrivalAirport();
                    DateFormat df = new SimpleDateFormat("MM/dd/yy HH:mm");
                    row[3] = df.format(flight.getDepartureDate());
                    String seatString = "R:" + (i+1) + "C:" + (j+1);
                    row[4] = seatString;
                    dtm.addRow(row);
                    }
                }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeats = new javax.swing.JTable();

        tblSeats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Departure", "Arrival", "Date", "Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSeats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSeats;
    // End of variables declaration//GEN-END:variables
}
