/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.flight;

import business.Airlines;
import business.Fleet;
import business.Flight;
import business.FlightCatalog;
import business.Plane;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author runyangzhou
 */
public class FlightCreateJPanel extends javax.swing.JPanel {
    private JPanel displayJPanel;
    private FlightCatalog flightCatalog;
    private Airlines airlines;
    private String[] place = {"Shanghai","Boston","New York","Tokyo","Toronto","London","Paris","Seattle","Chicago","Cancun","Orlando"};
    private int[] year;
    private int[] month;
    private int[] day;
    private int[] hour;
    private int[] minute;
//    private int[] second;
    /**
     * Creates new form FlightCreateJPanel
     */
    public FlightCreateJPanel(JPanel displayJPanel, FlightCatalog flightCatalog, Airlines airlines) {
        initComponents();
        year = new int[1];
        year[0] = 18;
        month = new int[2];
        month[0] = 11;
        month[1] = 12;
        day = new int[31];
        hour = new int[24];
        minute = new int[60];
//        second = new int[60];
        for(int i = 0; i< day.length; i++){
            day[i] = i+1;
        }
        for(int i = 0; i< hour.length; i++){
            hour[i] = i;
        }
        for(int i = 0; i< minute.length; i++){
            minute[i] = i;
        }
//        for(int i = 0; i< second.length; i++){
//            second[i] = i;
//        }
        this.displayJPanel = displayJPanel;
        this.flightCatalog = flightCatalog;
        this.airlines = airlines;
        for(Fleet fleet : airlines.getFleetList())
                for(Plane plane : fleet.getPlaneList())
                    comboBoxSerialNumber.addItem(plane);
        for(String s : place){
            comboBoxDeparture.addItem(s);
        }
        for(String s : place){
            comboBoxArrival.addItem(s);
        }
        for(int i: year){
            comboBoxYear.addItem(i);
        }
        for(int i: month){
            comboBoxMonth.addItem(i);
        }
        for(int i: day){
            comboBoxDay.addItem(i);
        }
        for(int i: hour){
            comboBoxHour.addItem(i);
        }
        for(int i: minute){
            comboBoxMinute.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxSerialNumber = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboBoxDeparture = new javax.swing.JComboBox();
        comboBoxArrival = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxYear = new javax.swing.JComboBox();
        comboBoxMonth = new javax.swing.JComboBox();
        comboBoxDay = new javax.swing.JComboBox();
        btnCreate = new javax.swing.JButton();
        comboBoxHour = new javax.swing.JComboBox();
        comboBoxMinute = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Serial Number:");

        jLabel2.setText("Departure Airport:");

        jLabel3.setText("Arrival Airport:");

        jLabel4.setText("Date:");

        comboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxYearActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        comboBoxHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHourActionPerformed(evt);
            }
        });

        jLabel5.setText("Time:");

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboBoxArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboBoxDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreate)
                        .addGap(124, 124, 124)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(29, 29, 29))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxYearActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(((String) comboBoxDeparture.getSelectedItem()).equals((String) comboBoxArrival.getSelectedItem())){
            JOptionPane.showMessageDialog(null, "Arrival and departure cannot be the same");
        }
        else if((int) comboBoxDay.getSelectedItem() == 31 && (int) comboBoxMonth.getSelectedItem() == 11){
            JOptionPane.showMessageDialog(null, "Wrong date");
        }
        else{
            Flight flight = flightCatalog.addFlight();
            flight.setPlane((Plane) comboBoxSerialNumber.getSelectedItem());
            flight.setArrivalAirport((String) comboBoxArrival.getSelectedItem());
            flight.setDepartureAirport((String) comboBoxDeparture.getSelectedItem());
            String date = "";
            date = (int)comboBoxMonth.getSelectedItem()+ "/" + (int)comboBoxDay.getSelectedItem() + "/"
                    +(int)comboBoxYear.getSelectedItem()+ " " + (int)comboBoxHour.getSelectedItem() + ":"
                    +(int)comboBoxMinute.getSelectedItem();
            DateFormat df = new SimpleDateFormat("MM/dd/yy HH:mm");
            try {
                flight.setDepartureDate(df.parse(date));;
            } catch (ParseException ex) {
                Logger.getLogger(FlightCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            flight.setPlane((Plane) comboBoxSerialNumber.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Create new flight successfully");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void comboBoxHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxHourActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        displayJPanel.remove(this);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.previous(displayJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox comboBoxArrival;
    private javax.swing.JComboBox comboBoxDay;
    private javax.swing.JComboBox comboBoxDeparture;
    private javax.swing.JComboBox comboBoxHour;
    private javax.swing.JComboBox comboBoxMinute;
    private javax.swing.JComboBox comboBoxMonth;
    private javax.swing.JComboBox comboBoxSerialNumber;
    private javax.swing.JComboBox comboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
