/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
import information.*;
import javax.swing.JOptionPane;
/**
 *
 * @author runyangzhou
 */
public class AccountJPanel extends javax.swing.JPanel {

    
    private Person person;
//    private Account savingAccount;
//    private Account checkingAccount;
    
    public AccountJPanel(Person person) {
        this.person = person;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountSplitPane = new javax.swing.JSplitPane();
        accountDisplayJPanel = new javax.swing.JPanel();
        accountControlJPanel = new javax.swing.JPanel();
        accountCreateBtn = new javax.swing.JButton();
        account = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout accountDisplayJPanelLayout = new javax.swing.GroupLayout(accountDisplayJPanel);
        accountDisplayJPanel.setLayout(accountDisplayJPanelLayout);
        accountDisplayJPanelLayout.setHorizontalGroup(
            accountDisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );
        accountDisplayJPanelLayout.setVerticalGroup(
            accountDisplayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        accountSplitPane.setRightComponent(accountDisplayJPanel);

        accountCreateBtn.setText("Create");
        accountCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountCreateBtnActionPerformed(evt);
            }
        });

        account.setText("View");
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountControlJPanelLayout = new javax.swing.GroupLayout(accountControlJPanel);
        accountControlJPanel.setLayout(accountControlJPanelLayout);
        accountControlJPanelLayout.setHorizontalGroup(
            accountControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountControlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountControlJPanelLayout.setVerticalGroup(
            accountControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountControlJPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(accountCreateBtn)
                .addGap(55, 55, 55)
                .addComponent(account)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        accountSplitPane.setLeftComponent(accountControlJPanel);

        add(accountSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void accountCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountCreateBtnActionPerformed
        // TODO add your handling code here:
        AccountCreateJPanel accountCreateJPanel = new AccountCreateJPanel(person);
        accountSplitPane.setRightComponent(accountCreateJPanel);
    }//GEN-LAST:event_accountCreateBtnActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
        if(person.getCheckingAccount() == null){
            JOptionPane.showMessageDialog(null, "No Checking Account Information Created Yet!");
        }
        else if(person.getSavingAccount() == null){
            JOptionPane.showMessageDialog(null, "No Saving Account Information Created Yet!");
        }
        else{
            AccountViewJPanel accountViewJPanel = new AccountViewJPanel(person);
            accountSplitPane.setRightComponent(accountViewJPanel);
        }
    }//GEN-LAST:event_accountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account;
    private javax.swing.JPanel accountControlJPanel;
    private javax.swing.JButton accountCreateBtn;
    private javax.swing.JPanel accountDisplayJPanel;
    private javax.swing.JSplitPane accountSplitPane;
    // End of variables declaration//GEN-END:variables
}
