/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
import information.*;
/**
 *
 * @author runyangzhou
 */
public class AccountViewJPanel extends javax.swing.JPanel {

    private Person person;
    private Account savingAccount;
    private Account checkingAccount;
    
    public AccountViewJPanel(Person person) {
        this.person = person;
        initComponents();
        
        savingAccount = person.getSavingAccount();
        checkingAccount = person.getCheckingAccount();
        
        savingAccountBankNumberLabel.setText(savingAccount.getBankNumber());
        savingAccountBankRoutingNumberLabel.setText(savingAccount.getBankRoutingNumber());
        savingAccountBankAccountNumberLabel.setText(savingAccount.getBankAccountNumber());
        savingAccountBalanceLabel.setText(String.valueOf(savingAccount.getBalance()));
        
        checkingAccountBankNumberLabel.setText(checkingAccount.getBankNumber());
        checkingAccountBankRoutingNumberLabel.setText(checkingAccount.getBankRoutingNumber());
        checkingAccountBankAccountNumberLabel.setText(checkingAccount.getBankAccountNumber());
        checkingAccountBalanceLabel.setText(String.valueOf(checkingAccount.getBalance()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkingAccountBankNumberLabel = new javax.swing.JLabel();
        savingAccountBankNumberLabel = new javax.swing.JLabel();
        checkingAccountBankRoutingNumberLabel = new javax.swing.JLabel();
        savingAccountBankRoutingNumberLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        checkingAccountBankAccountNumberLabel = new javax.swing.JLabel();
        savingAccountBankAccountNumberLabel = new javax.swing.JLabel();
        savingAccountBalanceLabel = new javax.swing.JLabel();
        checkingAccountBalanceLabel = new javax.swing.JLabel();

        jLabel1.setText("View Account Information");

        jLabel2.setText("Checking Account");

        jLabel3.setText("Saving Account");

        jLabel4.setText("Bank Number");

        jLabel9.setText("Bank Routing Number");

        jLabel10.setText("Bank Account Number");

        jLabel11.setText("Balance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(checkingAccountBankNumberLabel)
                    .addComponent(checkingAccountBankRoutingNumberLabel)
                    .addComponent(checkingAccountBankAccountNumberLabel)
                    .addComponent(checkingAccountBalanceLabel))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingAccountBankNumberLabel)
                    .addComponent(jLabel3)
                    .addComponent(savingAccountBankRoutingNumberLabel)
                    .addComponent(savingAccountBankAccountNumberLabel)
                    .addComponent(savingAccountBalanceLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(checkingAccountBankNumberLabel)
                    .addComponent(savingAccountBankNumberLabel))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkingAccountBankRoutingNumberLabel)
                    .addComponent(savingAccountBankRoutingNumberLabel)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(checkingAccountBankAccountNumberLabel)
                    .addComponent(savingAccountBankAccountNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(savingAccountBalanceLabel)
                    .addComponent(checkingAccountBalanceLabel))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkingAccountBalanceLabel;
    private javax.swing.JLabel checkingAccountBankAccountNumberLabel;
    private javax.swing.JLabel checkingAccountBankNumberLabel;
    private javax.swing.JLabel checkingAccountBankRoutingNumberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel savingAccountBalanceLabel;
    private javax.swing.JLabel savingAccountBankAccountNumberLabel;
    private javax.swing.JLabel savingAccountBankNumberLabel;
    private javax.swing.JLabel savingAccountBankRoutingNumberLabel;
    // End of variables declaration//GEN-END:variables
}
