/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import information.*;
import javax.swing.JOptionPane;

/**
 *
 * @author runyangzhou
 */
public class AddressJPanel extends javax.swing.JPanel {

    private Person person;
    
    
    /**
     * Creates new form AddressJPanel
     */
    public AddressJPanel(Person person) {
        this.person = person;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressSplitPane = new javax.swing.JSplitPane();
        addressControlJPanel = new javax.swing.JPanel();
        addressCreateBtn = new javax.swing.JButton();
        addressViewBtn = new javax.swing.JButton();
        addressDisPlayJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        addressCreateBtn.setText("Create");
        addressCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressCreateBtnActionPerformed(evt);
            }
        });

        addressViewBtn.setText("View");
        addressViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addressControlJPanelLayout = new javax.swing.GroupLayout(addressControlJPanel);
        addressControlJPanel.setLayout(addressControlJPanelLayout);
        addressControlJPanelLayout.setHorizontalGroup(
            addressControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressControlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressCreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addressControlJPanelLayout.setVerticalGroup(
            addressControlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressControlJPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(addressCreateBtn)
                .addGap(55, 55, 55)
                .addComponent(addressViewBtn)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        addressSplitPane.setLeftComponent(addressControlJPanel);

        javax.swing.GroupLayout addressDisPlayJPanelLayout = new javax.swing.GroupLayout(addressDisPlayJPanel);
        addressDisPlayJPanel.setLayout(addressDisPlayJPanelLayout);
        addressDisPlayJPanelLayout.setHorizontalGroup(
            addressDisPlayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );
        addressDisPlayJPanelLayout.setVerticalGroup(
            addressDisPlayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        addressSplitPane.setRightComponent(addressDisPlayJPanel);

        add(addressSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addressCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressCreateBtnActionPerformed
        // TODO add your handling code here:
        AddressCreateJPanel addressCreateJPanel = new AddressCreateJPanel(person);
        addressSplitPane.setRightComponent(addressCreateJPanel);
    }//GEN-LAST:event_addressCreateBtnActionPerformed

    private void addressViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressViewBtnActionPerformed
        // TODO add your handling code here:
        if(person.getAddress() == null){
            JOptionPane.showMessageDialog(null, "No Address Information Created Yet!");
        }
        else{
            AddressViewJPanel addressViewJPanel = new AddressViewJPanel(person);
            addressSplitPane.setRightComponent(addressViewJPanel);
        }
    }//GEN-LAST:event_addressViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressControlJPanel;
    private javax.swing.JButton addressCreateBtn;
    private javax.swing.JPanel addressDisPlayJPanel;
    private javax.swing.JSplitPane addressSplitPane;
    private javax.swing.JButton addressViewBtn;
    // End of variables declaration//GEN-END:variables
}
