/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
import information.*;
/**
 *
 * @author runyangzhou
 */
public class DisplayJPanel extends javax.swing.JPanel {
    private Person person;
    /**
     * Creates new form DisplayJPanel
     */
    public DisplayJPanel(Person person) {
        this.person = person;
        initComponents();
        
        PersonViewJPanel personViewJPanel = new PersonViewJPanel(person);
        displayTabbedPane.setComponentAt(0, personViewJPanel);
        
        AddressViewJPanel addressViewJPanel = new AddressViewJPanel(person);
        displayTabbedPane.setComponentAt(1, addressViewJPanel);
        
        AccountViewJPanel accountViewJPanel = new AccountViewJPanel(person);
        displayTabbedPane.setComponentAt(2, accountViewJPanel);
        
        DriverLisenceViewJPanel driverLisenceViewJPanel = new DriverLisenceViewJPanel(person);
        displayTabbedPane.setComponentAt(3, driverLisenceViewJPanel);
        
        MedicalRecordViewJPanel medicalRecordViewJPanel = new MedicalRecordViewJPanel(person);
        displayTabbedPane.setComponentAt(4, medicalRecordViewJPanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayTabbedPane = new javax.swing.JTabbedPane();
        personLayeredPane = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        addressLayeredPane = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        accountLayeredPane = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        driverLisenceLayeredPane = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        medicalRecordLayeredPane = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        personLayeredPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        personLayeredPane.add(jPanel1, java.awt.BorderLayout.CENTER);

        displayTabbedPane.addTab("Person", personLayeredPane);

        addressLayeredPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        addressLayeredPane.add(jPanel2, java.awt.BorderLayout.CENTER);

        displayTabbedPane.addTab("Address", addressLayeredPane);

        accountLayeredPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        accountLayeredPane.add(jPanel3, java.awt.BorderLayout.CENTER);

        displayTabbedPane.addTab("Account", accountLayeredPane);

        driverLisenceLayeredPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        driverLisenceLayeredPane.add(jPanel4, java.awt.BorderLayout.CENTER);

        displayTabbedPane.addTab("Driver's Lisence", driverLisenceLayeredPane);

        medicalRecordLayeredPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        medicalRecordLayeredPane.add(jPanel5, java.awt.BorderLayout.CENTER);

        displayTabbedPane.addTab("Medical Record", medicalRecordLayeredPane);

        add(displayTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane accountLayeredPane;
    private javax.swing.JLayeredPane addressLayeredPane;
    private javax.swing.JTabbedPane displayTabbedPane;
    private javax.swing.JLayeredPane driverLisenceLayeredPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLayeredPane medicalRecordLayeredPane;
    private javax.swing.JLayeredPane personLayeredPane;
    // End of variables declaration//GEN-END:variables
}
