/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface;
//import information.Person;
import information.*;
import java.sql.Date;
/**
 *
 * @author runyangzhou
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private Person person;
    
    public MainJFrame() {
        initComponents();
//        person.getAge();
        person = new Person();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        personInformationBtn = new javax.swing.JButton();
        addressBtn = new javax.swing.JButton();
        accountBtn = new javax.swing.JButton();
        driverLisenceBtn = new javax.swing.JButton();
        medicalRecordBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        createViewJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(666, 104));

        personInformationBtn.setText("Person Information");
        personInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personInformationBtnActionPerformed(evt);
            }
        });

        addressBtn.setText("Address");
        addressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressBtnActionPerformed(evt);
            }
        });

        accountBtn.setText("Account");
        accountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtnActionPerformed(evt);
            }
        });

        driverLisenceBtn.setText("Driver's Lisence");
        driverLisenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLisenceBtnActionPerformed(evt);
            }
        });

        medicalRecordBtn.setText("Medical Record");
        medicalRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRecordBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Test Setting");
        //jButton1.setVisible(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(driverLisenceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicalRecordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlJPanelLayout.createSequentialGroup()
                        .addComponent(personInformationBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(personInformationBtn)
                .addGap(33, 33, 33)
                .addComponent(addressBtn)
                .addGap(28, 28, 28)
                .addComponent(accountBtn)
                .addGap(31, 31, 31)
                .addComponent(driverLisenceBtn)
                .addGap(27, 27, 27)
                .addComponent(medicalRecordBtn)
                .addGap(18, 18, 18)
                .addComponent(displayBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlJPanel);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText(" Management System");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Welcome to Personal Information");

        javax.swing.GroupLayout createViewJPanelLayout = new javax.swing.GroupLayout(createViewJPanel);
        createViewJPanel.setLayout(createViewJPanelLayout);
        createViewJPanelLayout.setHorizontalGroup(
            createViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createViewJPanelLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(createViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createViewJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createViewJPanelLayout.createSequentialGroup()
                        .addGroup(createViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))))
        );
        createViewJPanelLayout.setVerticalGroup(
            createViewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createViewJPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(createViewJPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personInformationBtnActionPerformed
        // TODO add your handling code here:
        PersonJPanel personJPanel = new PersonJPanel(person);
        splitPane.setRightComponent(personJPanel);
    }//GEN-LAST:event_personInformationBtnActionPerformed

    private void addressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressBtnActionPerformed
        // TODO add your handling code here:
        AddressJPanel addressJPanel = new AddressJPanel(person);
        splitPane.setRightComponent(addressJPanel);
    }//GEN-LAST:event_addressBtnActionPerformed

    private void accountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtnActionPerformed
        // TODO add your handling code here:
        AccountJPanel accountJPanel = new AccountJPanel(person);
        splitPane.setRightComponent(accountJPanel);
    }//GEN-LAST:event_accountBtnActionPerformed

    private void medicalRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRecordBtnActionPerformed
        // TODO add your handling code here:
        MedicalRecordJPanel medicalRecordJPanel = new MedicalRecordJPanel(person);
        splitPane.setRightComponent(medicalRecordJPanel);
    }//GEN-LAST:event_medicalRecordBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        DisplayJPanel displayJPanel = new DisplayJPanel(person);
        splitPane.setRightComponent(displayJPanel);
        
    }//GEN-LAST:event_displayBtnActionPerformed

    private void driverLisenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLisenceBtnActionPerformed
        // TODO add your handling code here:
        DriverLisenceJPanel driverLisenceJPanel = new DriverLisenceJPanel(person);
        splitPane.setRightComponent(driverLisenceJPanel);
    }//GEN-LAST:event_driverLisenceBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        person.setFirstName("Joe");
        person.setLastName("Smith");
        person.setSex("Male");
        person.setPhoneNumber("617-320-6734");
        person.setWeight(70.5);
        person.setHeight(180.5);
        String d = "1995-09-19";
        Date date = Date.valueOf(d);
        person.setBirthday(date);
        
        Account account1 = new Account();
        account1.setBankNumber("B Number");
        account1.setBankRoutingNumber("Routing");
        account1.setBankAccountNumber("Account");
        account1.setBalance(800.5);
        account1.setType("Checking");
        Account account2 = new Account();
        account2.setBankNumber("B Number");
        account2.setBankRoutingNumber("Routing");
        account2.setBankAccountNumber("Account");
        account2.setBalance(800.5);
        account2.setType("Saving");
        person.setCheckingAccount(account1);
        person.setSavingAccount(account2);
        
        Address address = new Address();
        address.setAddress("360 Huntington Street");
        address.setCity("Boston");
        address.setState("MA");
        address.setZIPCode("02115");
        person.setAddress(address);
        
        DriverLisence driverLisence = new DriverLisence();
        driverLisence.setLisenceNumber("83541234");
        d = "2018-02-12";
        date = Date.valueOf(d);
        driverLisence.setIssuedDate(date);
        d = "2022-02-12";
        date = Date.valueOf(d);
        driverLisence.setExpiredDate(date);
        driverLisence.setBloodType("A");
        driverLisence.setPath("/Users/runyangzhou/test.png");
        person.setDriverLisence(driverLisence);
        
        MedicalRecord medicalRecord = new MedicalRecord();
        medicalRecord.setMedicalRecordNumber("Med Record No.");
        medicalRecord.setAlergy1("Alergy Text 1");
        medicalRecord.setAlergy2("Alergy Text 2");
        medicalRecord.setAlergy3("Alergy Text 3");
        person.setMedicalRecord(medicalRecord);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn;
    private javax.swing.JButton addressBtn;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JPanel createViewJPanel;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton driverLisenceBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton medicalRecordBtn;
    private javax.swing.JButton personInformationBtn;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
