/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
import information.*;
/**
 *
 * @author runyangzhou
 */
public class MedicalRecordViewJPanel extends javax.swing.JPanel {
    private Person person;
    private MedicalRecord medicalRecord;
    /**
     * Creates new form MedicalRecordViewJPanel
     */
    public MedicalRecordViewJPanel(Person person) {
        this.person = person;
        initComponents();
        medicalRecord = person.getMedicalRecord();
        medicalRecordMedicalRecordNumberLabel.setText(medicalRecord.getMedicalRecordNumber());
        medicalRecordAlergy1Label.setText(medicalRecord.getAlergy1());
        medicalRecordAlergy2Label.setText(medicalRecord.getAlergy2());
        medicalRecordAlergy3Label.setText(medicalRecord.getAlergy3());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        medicalRecordMedicalRecordNumberLabel = new javax.swing.JLabel();
        medicalRecordAlergy1Label = new javax.swing.JLabel();
        medicalRecordAlergy2Label = new javax.swing.JLabel();
        medicalRecordAlergy3Label = new javax.swing.JLabel();

        jLabel1.setText("View Medical Record Information");

        jLabel2.setText("Medical Record Number");

        jLabel3.setText("Alergy 1");

        jLabel4.setText("Alergy 2");

        jLabel5.setText("Alergy 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicalRecordMedicalRecordNumberLabel)
                            .addComponent(medicalRecordAlergy2Label)
                            .addComponent(medicalRecordAlergy1Label)
                            .addComponent(medicalRecordAlergy3Label))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(medicalRecordMedicalRecordNumberLabel))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(medicalRecordAlergy1Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(medicalRecordAlergy2Label))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(medicalRecordAlergy3Label))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel medicalRecordAlergy1Label;
    private javax.swing.JLabel medicalRecordAlergy2Label;
    private javax.swing.JLabel medicalRecordAlergy3Label;
    private javax.swing.JLabel medicalRecordMedicalRecordNumberLabel;
    // End of variables declaration//GEN-END:variables
}
