/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;
import information.*;
/**
 *
 * @author runyangzhou
 */
public class PersonViewJPanel extends javax.swing.JPanel {

    private Person person;
    /**
     * Creates new form PersonViewJPanel
     */
    public PersonViewJPanel(Person person) {
        initComponents();
        this.person = person;
        personFirstNameLabel.setText(person.getFirstName());
        personLastNameLabel.setText(person.getLastName());
        personSexLabel.setText(person.getSex());
        personHeightLabel.setText(person.getHeight().toString());
        personWeightLabel.setText(person.getWeight().toString());
//        personAgeLabel.setText(person.getAge().toString());
        personPhoneNumberLabel.setText(person.getPhoneNumber());
        personBirthdayLabel.setText(person.getBirthday().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        personFirstNameLabel = new javax.swing.JLabel();
        personLastNameLabel = new javax.swing.JLabel();
        personSexLabel = new javax.swing.JLabel();
        personPhoneNumberLabel = new javax.swing.JLabel();
        personWeightLabel = new javax.swing.JLabel();
        personHeightLabel = new javax.swing.JLabel();
        personBirthdayLabel = new javax.swing.JLabel();

        jLabel2.setText("First Name");

        jLabel7.setText("Height");

        jLabel6.setText("Weight");

        jLabel1.setText("View Person Information");

        jLabel4.setText("Sex");

        jLabel5.setText("Phone-number");

        jLabel3.setText("Last Name");

        jLabel8.setText("Birthday(YYYY/MM/DD)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personFirstNameLabel)
                            .addComponent(personLastNameLabel)
                            .addComponent(personSexLabel)
                            .addComponent(personPhoneNumberLabel)
                            .addComponent(personWeightLabel)
                            .addComponent(personHeightLabel)
                            .addComponent(personBirthdayLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personFirstNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(personLastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(personSexLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(personPhoneNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(personWeightLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(personHeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(personBirthdayLabel))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel personBirthdayLabel;
    private javax.swing.JLabel personFirstNameLabel;
    private javax.swing.JLabel personHeightLabel;
    private javax.swing.JLabel personLastNameLabel;
    private javax.swing.JLabel personPhoneNumberLabel;
    private javax.swing.JLabel personSexLabel;
    private javax.swing.JLabel personWeightLabel;
    // End of variables declaration//GEN-END:variables
}
